import {
  Box,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Flex,
  Heading,
  Button,
  SimpleGrid,
  Table,
  Thead,
  Tbody,
  Th,
  Tr,
  Td,
} from "@chakra-ui/react";

function App() {
  return (
    <>
      <SimpleGrid columns={1} gap={5}>
        <Box>
          {/*table>Thead>Tr>Th*4>lorem1^^^Tbody>Tr*5>Td*4>lorem1*/}
          <Table>
            <Thead>
              <Tr>
                <Th>Lorem.</Th>
                <Th>Error!</Th>
                <Th>Ipsam?</Th>
                <Th>In!</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Iusto?</Td>
                <Td>Libero?</Td>
                <Td>Dolores!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Assumenda.</Td>
                <Td>Quis.</Td>
                <Td>Asperiores!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Tenetur.</Td>
                <Td>Quae.</Td>
                <Td>Eos.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Maxime.</Td>
                <Td>Cumque.</Td>
                <Td>Aliquid.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Nam.</Td>
                <Td>Odit.</Td>
                <Td>Fugit.</Td>
              </Tr>
            </Tbody>
          </Table>
        </Box>
        {/*Box>Table[variant=striped]>Thead>Tr>Th*4>lorem1^^^Tbody>Tr*5>Td*4>lorem1*/}
        <Box>
          <Table variant="striped" colorScheme="red" size={"md"}>
            <Thead>
              <Tr>
                <Th>Lorem.</Th>
                <Th>Soluta!</Th>
                <Th>Ex!</Th>
                <Th>Natus!</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Optio!</Td>
                <Td>Neque!</Td>
                <Td>Dolorum.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Voluptatibus!</Td>
                <Td>Praesentium?</Td>
                <Td>Illo.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Fuga.</Td>
                <Td>Consequatur!</Td>
                <Td>Consequatur?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Obcaecati.</Td>
                <Td>Veritatis!</Td>
                <Td>Cumque?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Assumenda.</Td>
                <Td>Reiciendis?</Td>
                <Td>Aliquid?</Td>
              </Tr>

              <Tr>
                <Td>Lorem.</Td>
                <Td>Eius.</Td>
                <Td>Soluta!</Td>
                <Td>Soluta.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Vel.</Td>
                <Td>At.</Td>
                <Td>Unde?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Nihil!</Td>
                <Td>Dolor.</Td>
                <Td>Voluptatum.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Fuga!</Td>
                <Td>Suscipit?</Td>
                <Td>Nesciunt.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Unde.</Td>
                <Td>Non?</Td>
                <Td>Atque.</Td>
              </Tr>

              <Tr>
                <Td>Lorem.</Td>
                <Td>Obcaecati?</Td>
                <Td>Debitis.</Td>
                <Td>Tempora?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Animi.</Td>
                <Td>Voluptates?</Td>
                <Td>Blanditiis!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Doloribus?</Td>
                <Td>Eos.</Td>
                <Td>Odit!</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Molestias.</Td>
                <Td>Suscipit!</Td>
                <Td>Quae?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Itaque.</Td>
                <Td>Quisquam?</Td>
                <Td>Tempore?</Td>
              </Tr>

              <Tr>
                <Td>Lorem.</Td>
                <Td>Sapiente?</Td>
                <Td>Eligendi!</Td>
                <Td>Sint.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Pariatur?</Td>
                <Td>Sed.</Td>
                <Td>Iure.</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Dignissimos.</Td>
                <Td>Quis.</Td>
                <Td>Aliquid?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Dolorem?</Td>
                <Td>At.</Td>
                <Td>Totam?</Td>
              </Tr>
              <Tr>
                <Td>Lorem.</Td>
                <Td>Sunt?</Td>
                <Td>Animi?</Td>
                <Td>Quam?</Td>
              </Tr>
            </Tbody>
          </Table>
        </Box>
      </SimpleGrid>
    </>
  );
}

export default App;
